### ISSUE TITLE
训练的yolov5s版本

### ISSUE THREAD

**Issue by CasonTsai** [midasklr/yolov5ncnn#1]
现在官方的yolov5训练代码有好几版 ，请问大佬训练的yolov5s版本是4.0那个么，部署于ncnn速度怎样额

**Comment by midasklr** [comment]
> 现在官方的yolov5训练代码有好几版 ，请问大佬训练的yolov5s版本是4.0那个么，部署于ncnn速度怎样额

使用的是最新的v5.0 速度在骁龙855+输入416速度8fps左右

**Comment by CasonTsai** [comment]
谢谢大佬
